version: "3"

services:
  app:
    container_name: nodejs-react-challenge-dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 14
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
